version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Game_app/dino-game
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu       # Use ubuntu user on Ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
# ValidateService:
